### ISSUE TITLE
3 Questions.

### ISSUE THREAD

**Issue by ret394** [ssloy/triador#4]
Is this the ENIAC?
If not, how is it a computer?
Who paid for the hardware? the Government?

**Comment by ssloy** [comment]
I am not sure to understand the question. Apart from being able to compute things and being powered by electricity, ENIAC and my computer have little in common. It is my pet project and thus I pay for the hardware from my pocket.

**Comment by ret394** [comment]
History can't ... Oh wait! I see. You want me to teach you about the ENIAC?

You are more shrewd than I thought. Nice! 😻

**Comment by ret394** [comment]
I'll hide the above comment once you ack it.

**Comment by ret394** [comment]
Thanks. closing to avoid as Men⬆.
